% vi: noexpandtab:tabstop=4:ft=gprolog
% Copyright (c) 2024 Sergey Sikorskiy, released under the GNU GPLv2 license.

% man mkfs.f2fs
% f2fs_feat(name, depends_list)
prop_info(f2fs_feat, feat4s('-O', ',', on_off), [
	  prop_feat4(encrypt, off, std, attr([], ''))
	, prop_feat4(extra_attr, off, std, attr([], ''))
	, prop_feat4(project_quota, off, std, attr([extra_attr], ''))
	, prop_feat4(inode_checksum, off, std, attr([extra_attr], ''))
	, prop_feat4(flexible_inline_xattr, off, std, attr([extra_attr], ''))
	, prop_feat4(quota, off, std, attr([], ''))
	, prop_feat4(inode_crtime, off, std, attr([extra_attr], ''))
	, prop_feat4(lost_found, off, std, attr([], ''))
	, prop_feat4(verity, off, std, attr([], ''))
	, prop_feat4(sb_checksum, off, std, attr([], ''))
	, prop_feat4(casefold, off, std, attr([], ''))
	, prop_feat4(compression, off, std, attr([extra_attr], ''))
	]).

prop_info(f2fs_rw, opt4s(' '), [
	  opt4('heap-based-allocation', enum([0, 1]), 1, '-a')
	% , opt4('device-list', int, 0, '-c')
	, opt4('debug-level', int, 0, '-d')
	% , opt4('extension-list', int, 0, '-e')
	% , opt4('extension-list', int, 0, '-E')
	, opt4('force', enable, no, '-f')
	% , opt4('default-options', int, 0, '-g')
	, opt4('extended node bitmap', enable, no, '-i')
	, opt4('label', str, '', '-l')
	, opt4('block zoned', enable, no, '-m')
	, opt4('overprovision-ratio', percentage, 5, '-o')
	% , opt4('casefolding encoding:flags', int, 0, '-C')
	, opt4('disable checkpointing srand seed', enable, no, '-r')
	% , opt4('uid:gid"', int, 0, '-R')
	, opt4('segments per section', int, 1, '-s')
	, opt4('sparse mode', enable, no, '-S')
	, opt4('discard policy', enum([0, 1]), 1, '-t')
	, opt4('timestamp', int, -1, '-T')
	, opt4('wanted-sector-size', size, 0, '-w')
	, opt4('sections-per-zone', int, 1, '-z')
	]).

prop_info(mnt_f2fs_feat, feat4s('--options', ',', on_off), [
	  prop_feat4(age_extent_cache, off, std, none)
	, prop_feat4(atgc, off, std, none)
	, prop_feat4(barrier, off, pref1(no), none)
	, prop_feat4(checkpoint_merge, off, pref1(no), none)
	, prop_feat4(compress_cache, off, std, none)
	, prop_feat4(compress_chksum, off, std, none)
	, prop_feat4(data_flush, off, std, none)
	, prop_feat4(disable_ext_identify, off, std, none)
	, prop_feat4(disable_roll_forward, off, std, none)
	, prop_feat4(discard, off, pref1(no), none)
	, prop_feat4(extent_cache, off, pref1(no), none)
	, prop_feat4(fastboot, off, std, none)
	, prop_feat4(flush_merge, off, std, none)
	, prop_feat4(gc_merge, off, pref1(no), none)
	, prop_feat4(grpquota, off, std, none)
	, prop_feat4(inline_data, on, pref1(no), none)
	, prop_feat4(inline_dentry, off, pref1(no), none)
	, prop_feat4(inline_xattr, off, pref1(no), none)
	, prop_feat4(inlinecrypt, off, std, none)
	, prop_feat4(noacl, off, std, none)
	, prop_feat4(norecovery, off, std, none)
	, prop_feat4(nouser_xattr, off, std, none)
	, prop_feat4(offgrpjquota, off, std, none)
	, prop_feat4(offprjjquota, off, std, none)
	, prop_feat4(offusrjquota, off, std, none)
	, prop_feat4(prjquota, off, std, none)
	, prop_feat4(quota, off, pref1(no), none)
	, prop_feat4(test_dummy_encryption, off, std, none)
	, prop_feat4(usrquota, off, std, none)
	]).

prop_info(mnt_f2fs_opt, opt3s('--options', ','), [
	  opt3(active_logs, enum(2, 4, 6), 6)
	, opt3(alloc_mode, enum(default, reuse), default)
	, opt3(background_gc, enum(on, off, sync), on)
	, opt3(checkpoint, enum(disable, enable), enable)
	, opt3(compress_algorithm, enum(default, lzo, lz4, zstd, 'lzo-rle'), default)
	% , opt3(compress_algorithm, enum(default, lz4, zstd), default)
	, opt3(compress_extension, str, '')
	, opt3(compress_log_size, size, '16KB')
	, opt3(compress_mode, enum(fs, user), fs)
	, opt3(discard_unit, enum(block, segment, section), block)
	, opt3(errors, enum(panic, continue, 'remount-ro'), continue)
	, opt3(fault_injection, int, 0)
	, opt3(fault_type, int, 0)
	, opt3(fsync_mode, enum(posix, strict, nobarrier), posix)
	, opt3(grpjquota, file, '')
	, opt3(inline_xattr_size, int, 0)
	, opt3(io_bits, int, 0)
	, opt3(jqfmt, enum(vfsold, vfsv0, vfsv1), vfsv1)
	, opt3(memory, enum(normal, low), normal)
	, opt3(mode, enum(adaptive, lfs), adaptive)
	, opt3(nocompress_extension, str, '')
	, opt3(prjjquota, file, '')
	, opt3(reserve_root, int, 0)
	, opt3(resgid, int, 0)
	, opt3(resuid, int, 0)
	, opt3(test_dummy_encryption, enum(none, v1, v2), none)
	, opt3(usrjquota, file, '')
	]).


